project_id = "igrpbeordzwcsxihlwny"

[functions.twilio-webhooks]
verify_jwt = false

[functions.legal-chatbot]
verify_jwt = false

[functions.generate-legal-analysis]
verify_jwt = false

[functions.generate-proposal]
verify_jwt = false

[functions.log-chat-message]
verify_jwt = true

[functions.notify-new-signup]
verify_jwt = false