-- Continue populating legal database with remaining categories

-- Business Formation & Investment Articles (20 new)
INSERT INTO legal_knowledge (title, category, subcategory, content, keywords, tags, law_reference, article_number, language) VALUES
('LLC Formation for Foreign Investors', 'Business', 'Company Formation', 'Limited Liability Companies (LLC) popular structure for foreign investors. Minimum capital: EGP 50,000. Maximum partners: 50. Foreign ownership: up to 100% in most sectors. Formation process: name reservation, articles of association, capital deposit, commercial registration, tax registration. Required documents: partnership agreement, capital proof, partners identification. Formation time: 30-45 days. Professional legal assistance recommended.', ARRAY['LLC', 'limited liability company', 'foreign investment', 'company formation'], ARRAY['business formation', 'LLC', 'investment'], 'Companies Law No. 159 of 1981', 'Article 15', 'en'),

('Joint Stock Company Establishment', 'Business', 'Company Formation', 'Joint stock companies for large-scale investments. Minimum capital: EGP 250,000 (public), EGP 50,000 (private). Share structure: registered and bearer shares allowed. Foreign shareholding permitted up to 100% unless restricted sector. Formation requirements: founders meeting, articles of incorporation, capital subscription, regulatory approvals. Public companies must list on Egyptian Exchange within 3 years. Board of directors mandatory.', ARRAY['joint stock company', 'shareholding', 'public company', 'private company'], ARRAY['corporations', 'shares', 'stock company'], 'Companies Law No. 159 of 1981', 'Article 45', 'en'),

('Partnership Structures with Egyptian Nationals', 'Business', 'Partnerships', 'Partnerships between foreign and Egyptian nationals regulated by Commercial Law. Types: general partnership, limited partnership, participation partnership. Partnership agreement must specify: profit sharing, management roles, capital contributions, dissolution procedures. Foreign partner liability varies by partnership type. Tax implications differ from corporate structures. Legal due diligence on Egyptian partners essential.', ARRAY['partnership', 'business partnership', 'foreign partnership', 'joint venture'], ARRAY['partnerships', 'joint ventures', 'collaboration'], 'Commercial Law No. 17 of 1999', 'Article 35', 'en'),

('Free Zone Investment Opportunities', 'Business', 'Free Zones', 'Egypt operates multiple free zones offering investment incentives: Suez Canal Economic Zone, Alexandria Free Zone, Cairo Free Zone. Benefits: tax exemptions, customs exemptions, 100% foreign ownership, simplified procedures. Eligible activities: manufacturing, logistics, services, technology. Investment requirements vary by zone. Applications through zone authorities. Long-term investment commitments required.', ARRAY['free zone', 'investment incentives', 'tax exemption', 'customs exemption'], ARRAY['free zones', 'investment', 'incentives'], 'Investment Law No. 72 of 2017', 'Article 45', 'en'),

('Licensing Requirements by Industry Sector', 'Business', 'Business Licensing', 'Industry-specific licensing requirements vary significantly. High-regulation sectors: banking, insurance, telecommunications, pharmaceuticals, tourism. Medium-regulation: manufacturing, retail, construction, transport. Low-regulation: consulting, trading, IT services. Applications through relevant ministries and authorities. Professional licensing may be required separately. Compliance monitoring ongoing. Penalties for unlicensed operations severe.', ARRAY['business license', 'industry licensing', 'sector regulations', 'professional licensing'], ARRAY['licensing', 'permits', 'regulations'], 'Business Licensing Law No. 141 of 2004', 'Article 8', 'en'),

('Tax Incentives for Foreign Investment', 'Business', 'Tax Benefits', 'Egypt offers various tax incentives for foreign investment. New Capital Law incentives: 5-year tax holiday for qualifying projects, reduced corporate tax rates, customs duty exemptions. Upper Egypt incentives: 50% tax reduction for 10 years. Green economy incentives: additional tax benefits for renewable energy and environmental projects. Application through GAFI. Conditions and monitoring requirements apply.', ARRAY['tax incentives', 'investment incentives', 'tax holiday', 'GAFI'], ARRAY['tax benefits', 'incentives', 'investment'], 'Investment Law No. 72 of 2017', 'Article 18', 'en'),

('Import and Export Licensing Procedures', 'Business', 'Trade Licensing', 'Import/export activities require proper licensing and registration. Importer/exporter registration with Import and Export Control Authority (IECA). Product-specific licenses for controlled goods. Customs procedures: customs declaration, inspection, duty payment, release. Documentation requirements: commercial invoice, packing list, bill of lading, certificates of origin. Professional customs clearance agents recommended.', ARRAY['import license', 'export license', 'customs procedures', 'IECA'], ARRAY['import', 'export', 'trade'], 'Customs Law No. 207 of 2020', 'Article 25', 'en'),

('Intellectual Property Registration', 'Business', 'IP Protection', 'Intellectual property protection available for: trademarks, patents, copyrights, industrial designs. Registration through Egyptian Patent Office. Trademark protection: 10 years renewable. Patent protection: 20 years. Copyright protection: automatic, life plus 50 years. Madrid Protocol member for international trademark filing. Professional IP assistance recommended for complex applications. Enforcement through specialized IP courts.', ARRAY['intellectual property', 'trademark', 'patent', 'copyright'], ARRAY['IP protection', 'trademarks', 'patents'], 'Intellectual Property Law No. 82 of 2002', 'Article 12', 'en'),

('Commercial Registration Process', 'Business', 'Business Registration', 'Commercial registration mandatory for all business activities. Registration at Commercial Registry (General Authority for Investment). Required documents: articles of association, lease agreement, identity documents, capital proof. Registration fees based on capital amount. Publication in Official Gazette required. Registration certificate enables: bank account opening, tax registration, licensing applications. Annual renewal required.', ARRAY['commercial registration', 'business registration', 'commercial registry', 'GAFI'], ARRAY['registration', 'business licensing', 'commercial'], 'Commercial Law No. 17 of 1999', 'Article 18', 'en'),

('Banking Requirements for Business Accounts', 'Business', 'Banking', 'Business bank accounts required for Egyptian companies. Account opening requirements: commercial registration, tax card, articles of association, board resolution, beneficial ownership declarations. Minimum deposits vary by bank. Foreign exchange accounts permitted for qualifying businesses. Documentation for international transfers required. Professional banking relationships important for credit facilities.', ARRAY['business bank account', 'corporate banking', 'foreign exchange', 'bank requirements'], ARRAY['banking', 'business accounts', 'financial services'], 'Banking Law No. 194 of 2020', 'Article 45', 'en'),

('Capital Requirements by Business Type', 'Business', 'Capital Requirements', 'Minimum capital requirements vary by business structure and activity. LLC: EGP 50,000, Joint Stock Company: EGP 250,000 (public), Sole Proprietorship: no minimum. Banking sector: EGP 5 billion for banks. Insurance: EGP 100-500 million depending on type. Investment firms: EGP 10-50 million. Capital must be deposited before registration. Foreign currency capital allowed with Central Bank approval.', ARRAY['minimum capital', 'capital requirements', 'business capital', 'investment capital'], ARRAY['capital', 'business finance', 'requirements'], 'Companies Law No. 159 of 1981', 'Article 25', 'en'),

('Foreign Exchange Regulations for Businesses', 'Business', 'Foreign Exchange', 'Foreign exchange regulations govern international business transactions. Central Bank authorization required for: large foreign investments, international loans, profit repatriation. Documentation requirements for foreign transfers: commercial invoices, contracts, regulatory approvals. Exchange rate: market-determined with Central Bank intervention. Multiple currency accounts permitted for qualifying businesses. Compliance reporting required.', ARRAY['foreign exchange', 'currency regulations', 'central bank', 'international transfers'], ARRAY['forex', 'currency', 'international business'], 'Central Bank Law No. 194 of 2020', 'Article 65', 'en'),

('Contract Law Essentials for Foreign Businesses', 'Business', 'Contract Law', 'Egyptian contract law based on Civil Code principles. Essential contract elements: offer, acceptance, consideration, legal capacity. Written contracts recommended for significant transactions. Arabic translation required for legal proceedings. Governing law clauses: Egyptian law applies unless otherwise specified (limited exceptions). Dispute resolution: Egyptian courts have jurisdiction unless arbitration agreed. Professional legal review essential.', ARRAY['contract law', 'business contracts', 'legal agreements', 'contract terms'], ARRAY['contracts', 'legal agreements', 'business law'], 'Civil Code No. 131 of 1948', 'Article 89', 'en'),

('Corporate Governance Requirements', 'Business', 'Corporate Governance', 'Corporate governance requirements vary by company type and size. Joint stock companies: board of directors, audit committee, shareholders meetings. Listed companies: additional disclosure requirements, independent directors, corporate governance code compliance. LLC: management structure flexible. Foreign companies: local representation may be required. Regular reporting to regulators mandatory. Professional governance advice recommended.', ARRAY['corporate governance', 'board of directors', 'compliance', 'shareholders'], ARRAY['governance', 'compliance', 'corporate management'], 'Companies Law No. 159 of 1981', 'Article 85', 'en'),

('Merger and Acquisition Regulations', 'Business', 'M&A', 'Mergers and acquisitions subject to Egyptian competition law and sector-specific regulations. Competition Authority approval required for transactions above threshold values. Due diligence requirements: financial, legal, regulatory, tax. Foreign investment approvals may be needed. Employee protection regulations apply. Professional M&A advisors essential. Transaction structuring affects tax implications. Post-transaction integration compliance required.', ARRAY['merger', 'acquisition', 'M&A', 'competition law'], ARRAY['M&A', 'business transactions', 'competition'], 'Competition Law No. 3 of 2005', 'Article 15', 'en'),

('Bankruptcy and Liquidation Procedures', 'Business', 'Insolvency', 'Bankruptcy procedures govern insolvent companies and individuals. Company liquidation: voluntary or involuntary through Economic Courts. Liquidation process: asset valuation, creditor claims, asset distribution, company dissolution. Bankruptcy protection: restructuring procedures available. Director liabilities: personal liability for wrongful trading. Professional insolvency practitioners required. Cross-border insolvency recognition limited.', ARRAY['bankruptcy', 'liquidation', 'insolvency', 'company dissolution'], ARRAY['bankruptcy', 'insolvency', 'business closure'], 'Companies Law No. 159 of 1981', 'Article 165', 'en'),

('E-commerce Business Licensing', 'Business', 'Digital Business', 'E-commerce businesses require specific licensing and compliance. E-commerce license from Ministry of Trade and Industry required. Data protection compliance with Personal Data Protection Law. Consumer protection regulations apply to online sales. Tax registration for digital services. Website terms and conditions must comply with Egyptian law. Cross-border e-commerce additional requirements. Cybersecurity measures mandatory.', ARRAY['e-commerce', 'online business', 'digital commerce', 'internet business'], ARRAY['e-commerce', 'digital business', 'online retail'], 'E-Commerce Law No. 175 of 2018', 'Article 8', 'en'),

('Professional Service Firm Establishment', 'Business', 'Professional Services', 'Professional service firms (legal, accounting, engineering, medical) have special requirements. Professional syndicate membership mandatory. Partnership restrictions: only licensed professionals can be partners. Foreign professionals: license recognition procedures required. Liability insurance mandatory for some professions. Client confidentiality regulations strict. Professional ethics codes binding. Quality control and continuing education requirements.', ARRAY['professional services', 'law firm', 'accounting firm', 'consulting'], ARRAY['professional services', 'consulting', 'professional practice'], 'Professional Practice Laws (Various)', 'Article 12', 'en'),

('Manufacturing License Requirements', 'Business', 'Manufacturing', 'Manufacturing businesses require multiple licenses and permits. Industrial license from Ministry of Trade and Industry. Environmental permits for pollution-generating activities. Building permits for industrial facilities. Fire safety approvals. Workers health and safety compliance. Quality standards certification (Egyptian Standards Organization). Export licenses for international sales. Regular inspection and compliance monitoring.', ARRAY['manufacturing license', 'industrial license', 'factory permit', 'production license'], ARRAY['manufacturing', 'industrial', 'production'], 'Industrial Development Law No. 144 of 2006', 'Article 18', 'en'),

('Tourism Business Licensing and Regulations', 'Business', 'Tourism', 'Tourism businesses heavily regulated by Ministry of Tourism and Antiquities. License categories: travel agencies, tour operators, hotels, restaurants, transport. Licensing requirements: financial guarantees, professional qualifications, facility standards. Tourist guide licensing separate. Foreign tour operators: local partnership or representation required. Quality classification systems for hotels and restaurants. Regular inspections and compliance monitoring.', ARRAY['tourism license', 'travel agency', 'tour operator', 'hotel license'], ARRAY['tourism', 'hospitality', 'travel business'], 'Tourism Law No. 1 of 1983', 'Article 25', 'en');

-- Family Law for Expats Articles (18 new)
INSERT INTO legal_knowledge (title, category, subcategory, content, keywords, tags, law_reference, article_number, language) VALUES
('Mixed Nationality Marriage Procedures', 'Family Law', 'Marriage', 'Marriage between Egyptian and foreign nationals requires specific procedures. Civil marriage: at Egyptian Embassy abroad or Egyptian civil registry. Religious marriage: recognized if performed according to Egyptian religious law. Required documents: birth certificates, divorce/death certificates (if applicable), medical certificates, embassy certificates for foreigners. Translation and legalization required. Registration with Egyptian authorities mandatory.', ARRAY['mixed marriage', 'international marriage', 'marriage procedures', 'civil marriage'], ARRAY['marriage', 'international', 'civil procedures'], 'Personal Status Law No. 25 of 1929', 'Article 15', 'en'),

('Religious vs Civil Marriage Options', 'Family Law', 'Marriage Types', 'Egypt recognizes both religious and civil marriage. Religious marriage: Islamic, Christian, Jewish ceremonies according to respective religious laws. Civil marriage: available for non-Muslims, performed by authorized civil registrars. Legal effects: both types equally valid for inheritance, custody, divorce rights. Conversion considerations: religious marriage may require conversion in some cases. Documentation requirements vary by marriage type.', ARRAY['religious marriage', 'civil marriage', 'marriage types', 'religious conversion'], ARRAY['marriage', 'religious law', 'civil law'], 'Personal Status Law No. 25 of 1929', 'Article 8', 'en'),

('Prenuptial Agreements Enforcement', 'Family Law', 'Prenuptial Agreements', 'Prenuptial agreements (marriage contracts) enforceable under Egyptian law with limitations. Permissible clauses: property rights, financial arrangements, maintenance obligations. Prohibited clauses: child custody predetermination, Islamic inheritance law violations. Contract requirements: written form, witness signatures, notarization. Religious marriage contracts: additional Islamic law compliance required. Professional legal advice essential for enforceability.', ARRAY['prenuptial agreement', 'marriage contract', 'property rights', 'financial arrangements'], ARRAY['prenuptial', 'marriage contracts', 'property'], 'Personal Status Law No. 25 of 1929', 'Article 22', 'en'),

('Child Custody in International Marriages', 'Family Law', 'Child Custody', 'Child custody in international marriages complex area involving Egyptian and foreign laws. Egyptian law principles: mother custody until age 15 (boys), 16 (girls), then father custody. International considerations: Hague Convention application, foreign court recognition, travel restrictions. Best interests standard increasingly applied. Foreign parent rights: visitation, education decisions, travel consent. Legal representation essential for international custody cases.', ARRAY['child custody', 'international custody', 'hague convention', 'custody rights'], ARRAY['custody', 'children', 'international law'], 'Personal Status Law No. 25 of 1929', 'Article 45', 'en'),

('Divorce Procedures for Mixed Couples', 'Family Law', 'Divorce', 'Divorce procedures for mixed nationality couples depend on marriage type and applicable law. Islamic divorce: various forms including mutual consent (khula), husband divorce (talaq). Civil divorce: court proceedings required. Jurisdiction: Egyptian courts have jurisdiction for Egyptian residents. Foreign divorce recognition: requires Egyptian court validation. Property division, alimony, custody determined by applicable personal status law.', ARRAY['divorce procedures', 'mixed marriage divorce', 'international divorce', 'khula'], ARRAY['divorce', 'family court', 'international'], 'Personal Status Law No. 25 of 1929', 'Article 65', 'en'),

('Alimony and Financial Support Obligations', 'Family Law', 'Financial Support', 'Alimony and financial support obligations determined by Egyptian personal status law. Wife maintenance (nafaqah): mandatory during marriage and waiting period after divorce. Amount based on husband financial capacity and wife social status. Child support: mandatory until children reach independence. International enforcement: reciprocal enforcement agreements with some countries. Professional legal assistance recommended for cross-border enforcement.', ARRAY['alimony', 'nafaqah', 'child support', 'financial support'], ARRAY['alimony', 'financial support', 'maintenance'], 'Personal Status Law No. 25 of 1929', 'Article 75', 'en'),

('Child Support Across Borders', 'Family Law', 'Child Support', 'International child support enforcement challenging but possible. Egyptian courts can order support from Egyptian residents. International enforcement: depends on bilateral agreements and reciprocal enforcement treaties. Documentation requirements: paternity proof, custody orders, financial evidence. Collection mechanisms: asset seizure, travel restrictions, international cooperation. Professional international family law expertise essential.', ARRAY['international child support', 'cross-border support', 'child maintenance', 'support enforcement'], ARRAY['child support', 'international enforcement', 'cross-border'], 'Personal Status Law No. 25 of 1929', 'Article 85', 'en'),

('Adoption Laws for Foreign Nationals', 'Family Law', 'Adoption', 'Adoption laws in Egypt based on Islamic principles. Islamic law: adoption (tabanni) prohibited, fostering (kafala) permitted. Foster care (kafala): legal guardianship without inheritance rights or name change. Non-Muslim adoption: may be recognized if performed abroad before arriving in Egypt. International adoption: complex procedures, embassy involvement required. Legal consultation essential for understanding rights and limitations.', ARRAY['adoption', 'kafala', 'foster care', 'international adoption'], ARRAY['adoption', 'foster care', 'child welfare'], 'Personal Status Law No. 25 of 1929', 'Article 95', 'en'),

('Name Change Procedures After Marriage', 'Family Law', 'Name Changes', 'Name change procedures after marriage vary by circumstances. Wife name change: optional under Egyptian law, may retain maiden name. Documentation update: passport, identity documents, bank accounts, property records. Foreign spouse considerations: embassy procedures for passport updates. Professional name continuation: permitted in some professions. Legal documentation required for all official name changes.', ARRAY['name change', 'married name', 'identity documents', 'passport update'], ARRAY['name change', 'documentation', 'identity'], 'Civil Registration Law No. 143 of 1994', 'Article 18', 'en'),

('International Child Abduction Prevention', 'Family Law', 'Child Protection', 'International child abduction prevention measures under Hague Convention. Egypt signatory to 1980 Hague Convention on Child Abduction. Prevention measures: court orders restricting travel, passport surrender, embassy notifications. Wrongful removal procedures: return applications through Central Authority. Time limits: applications within one year of removal. Legal representation essential for Hague Convention proceedings.', ARRAY['child abduction', 'hague convention', 'wrongful removal', 'international custody'], ARRAY['child protection', 'abduction', 'hague convention'], 'International Child Abduction Law', 'Article 5', 'en'),

('Inheritance Rights in Mixed Marriages', 'Family Law', 'Inheritance', 'Inheritance rights in mixed marriages governed by Egyptian law for Egyptian residents. Islamic inheritance law: applies to Muslims regardless of nationality. Non-Muslim inheritance: Egyptian Civil Code application. Foreign spouse rights: inheritance limited by Egyptian law. Will preparation: important for non-Muslim couples to specify distribution. International estate planning: coordination with foreign inheritance laws required.', ARRAY['inheritance rights', 'mixed marriage inheritance', 'islamic inheritance', 'estate planning'], ARRAY['inheritance', 'estate planning', 'succession'], 'Inheritance Law No. 77 of 1943', 'Article 25', 'en'),

('Polygamy Laws and Foreign Spouses', 'Family Law', 'Polygamy', 'Polygamy permitted under Islamic law with specific conditions. Legal requirements: financial capacity, equal treatment, first wife notification. Foreign wife considerations: understanding of polygamous marriage laws. Legal protections: stipulations in marriage contract prohibiting polygamy. Court procedures: authorization may be required. Non-Muslim marriages: polygamy not permitted under Egyptian civil law.', ARRAY['polygamy', 'plural marriage', 'islamic marriage', 'marriage contract'], ARRAY['polygamy', 'marriage law', 'islamic law'], 'Personal Status Law No. 25 of 1929', 'Article 35', 'en'),

('Domestic Violence Protection for Foreigners', 'Family Law', 'Domestic Violence', 'Domestic violence protection available to all residents including foreigners. Legal protections: criminal law penalties, civil protection orders, emergency shelter access. Reporting procedures: police reports, medical documentation, witness statements. Support services: governmental and NGO assistance available. Embassy assistance: foreign nationals can seek embassy support. Language barriers: interpretation services available in legal proceedings.', ARRAY['domestic violence', 'protection orders', 'legal protection', 'embassy assistance'], ARRAY['domestic violence', 'protection', 'safety'], 'Domestic Violence Law No. 11 of 2017', 'Article 12', 'en'),

('Marriage Certificate Authentication', 'Family Law', 'Documentation', 'Marriage certificate authentication required for legal recognition. Egyptian marriages: automatic registration with civil registry. Foreign marriages: authentication through Egyptian embassy/consulate. Apostille/legalization: required for foreign marriage certificates. Translation requirements: certified Arabic translation mandatory. Legal effects: authenticated certificates recognized for all legal purposes including inheritance, custody, residence applications.', ARRAY['marriage certificate', 'authentication', 'apostille', 'legal recognition'], ARRAY['authentication', 'documentation', 'legal recognition'], 'Civil Registration Law No. 143 of 1994', 'Article 25', 'en'),

('Spousal Visa and Residence Rights', 'Family Law', 'Immigration Rights', 'Spousal visa and residence rights for foreign spouses of Egyptians. Residence permit: foreign spouse eligible for temporary residence permit. Application requirements: marriage certificate, medical examination, police clearance, financial support proof. Renewal procedures: annual renewal required initially. Permanent residence: available after 5 years continuous residence. Divorce effects: residence status may be affected by divorce.', ARRAY['spousal visa', 'residence permit', 'foreign spouse', 'immigration status'], ARRAY['immigration', 'residence', 'spousal rights'], 'Immigration Law No. 89 of 1960', 'Article 28', 'en'),

('Child Passport and Nationality Issues', 'Family Law', 'Child Nationality', 'Child nationality and passport issues in mixed marriages complex. Egyptian nationality: children of Egyptian fathers automatically Egyptian citizens. Mother nationality: transmission limited under Egyptian law. Dual nationality: Egypt recognizes dual nationality in limited circumstances. Passport applications: both parents consent usually required. Travel restrictions: may apply in custody disputes.', ARRAY['child nationality', 'dual citizenship', 'child passport', 'nationality law'], ARRAY['nationality', 'citizenship', 'children'], 'Nationality Law No. 26 of 1975', 'Article 15', 'en'),

('Guardianship Laws for Foreign Parents', 'Family Law', 'Guardianship', 'Guardianship laws affect foreign parents in Egypt. Legal guardianship: automatic for parents over their minor children. Limitations: travel restrictions may apply, especially for mothers. Court guardianship: may be required for specific legal acts. Foreign parent rights: generally equal to Egyptian parents for day-to-day care. Estate guardianship: special rules for managing child property. Professional legal guidance recommended for complex situations.', ARRAY['guardianship', 'parental rights', 'foreign parents', 'legal guardianship'], ARRAY['guardianship', 'parental rights', 'legal custody'], 'Personal Status Law No. 25 of 1929', 'Article 105', 'en'),

('Religious Conversion Requirements', 'Family Law', 'Religious Conversion', 'Religious conversion in family law context has legal implications. Marriage requirements: conversion may be required for religious marriage in some cases. Voluntary conversion: must be genuine and voluntary. Legal documentation: conversion certificate from religious authorities. Effects on family law: may affect divorce, custody, inheritance rights. Children impact: conversion may affect children legal status. Professional counseling and legal advice recommended.', ARRAY['religious conversion', 'conversion certificate', 'marriage conversion', 'religious requirements'], ARRAY['conversion', 'religious law', 'family law'], 'Personal Status Law No. 25 of 1929', 'Article 12', 'en');

-- Legal Procedures & Documentation Articles (20 new)
INSERT INTO legal_knowledge (title, category, subcategory, content, keywords, tags, law_reference, article_number, language) VALUES
('Power of Attorney for Foreign Nationals', 'Legal Procedures', 'Legal Documentation', 'Power of attorney essential for foreign nationals managing affairs in Egypt. Types: general, specific, durable power of attorney. Requirements: notarization, apostille/legalization, Arabic translation by certified translator. Scope: property transactions, business operations, court representation, government procedures. Revocation procedures: written notice, notarization required. Professional legal assistance recommended for complex powers.', ARRAY['power of attorney', 'legal representation', 'notarization', 'apostille'], ARRAY['legal documents', 'authorization', 'representation'], 'Civil Code No. 131 of 1948', 'Article 105', 'en'),

('Document Authentication and Apostille', 'Legal Procedures', 'Authentication', 'Document authentication essential for legal recognition in Egypt. Hague Apostille: for countries party to Hague Convention. Embassy legalization: for non-Hague countries through Egyptian embassy/consulate. Document types: birth certificates, marriage certificates, educational diplomas, commercial documents. Translation requirements: certified Arabic translation required. Professional authentication services available through legal service providers.', ARRAY['apostille', 'document authentication', 'embassy legalization', 'certified translation'], ARRAY['authentication', 'legalization', 'official documents'], 'International Documentation Law', 'Article 8', 'en'),

('Embassy and Consulate Services', 'Legal Procedures', 'Consular Services', 'Embassy and consulate services for foreign nationals in Egypt. Services provided: passport renewal, birth registration, death registration, notarial services, emergency assistance. Consular protection: assistance with legal problems, detention visits, emergency repatriation. Documentation services: certifying signatures, witnessing documents, providing certificates. Emergency services: 24-hour assistance for emergencies. Contact information maintained by embassies.', ARRAY['embassy services', 'consular services', 'consular protection', 'passport services'], ARRAY['embassy', 'consular', 'diplomatic services'], 'Vienna Convention on Consular Relations 1963', 'Article 5', 'en'),

('Legal Translation Requirements', 'Legal Procedures', 'Translation Services', 'Legal translation requirements strict in Egyptian legal system. Certified translators: must be authorized by Ministry of Justice or Egyptian Translators Syndicate. Document types requiring translation: contracts, court documents, certificates, academic credentials. Translation standards: accurate, complete, certified translation with translator signature and stamp. Oath translations: required for court proceedings. Professional translation services recommended for legal documents.', ARRAY['legal translation', 'certified translator', 'sworn translation', 'document translation'], ARRAY['translation', 'language services', 'legal documents'], 'Translator Licensing Law No. 51 of 1972', 'Article 12', 'en'),

('Court System Navigation for Foreigners', 'Legal Procedures', 'Court Procedures', 'Egyptian court system navigation guide for foreigners. Court hierarchy: Primary Courts, Courts of Appeal, Court of Cassation, Supreme Constitutional Court. Specialized courts: Economic Courts, Administrative Courts, Family Courts. Jurisdiction rules: civil, criminal, commercial, administrative matters. Language requirements: Arabic language proceedings, interpretation services available. Legal representation: mandatory for foreigners in most proceedings.', ARRAY['egyptian courts', 'court system', 'legal proceedings', 'court jurisdiction'], ARRAY['courts', 'legal system', 'litigation'], 'Judicial Authority Law No. 46 of 1972', 'Article 15', 'en'),

('Finding and Hiring Egyptian Lawyers', 'Legal Procedures', 'Legal Representation', 'Guide to finding and hiring Egyptian lawyers. Egyptian Bar Association: lawyer verification and complaint procedures. Specialization areas: commercial, civil, criminal, administrative, family law. Fee structures: hourly rates, fixed fees, contingency arrangements. Lawyer selection criteria: experience, specialization, language skills, international client experience. Professional conduct: ethical rules and disciplinary procedures. Legal aid: availability for low-income individuals.', ARRAY['egyptian lawyers', 'legal representation', 'bar association', 'legal fees'], ARRAY['lawyers', 'legal services', 'representation'], 'Advocacy Law No. 17 of 1983', 'Article 25', 'en'),

('Legal Aid Availability for Foreigners', 'Legal Procedures', 'Legal Aid', 'Legal aid services available to qualifying foreigners in Egypt. Eligibility criteria: financial need assessment, merit of case, residency status. Services covered: legal consultation, court representation, document preparation. Application procedures: legal aid offices, bar association programs, NGO services. Court-appointed counsel: available in criminal cases. Cost coverage: court fees, lawyer fees, expert fees. Language assistance: interpretation services provided.', ARRAY['legal aid', 'free legal services', 'court-appointed counsel', 'legal assistance'], ARRAY['legal aid', 'pro bono', 'legal assistance'], 'Legal Aid Law No. 123 of 2008', 'Article 8', 'en'),

('Notarization Procedures and Requirements', 'Legal Procedures', 'Notarization', 'Notarization procedures for documents in Egypt. Notary public services: authentication of signatures, document certification, oath administration. Required identification: passport, residence permit, national ID for eligible persons. Document types: contracts, powers of attorney, affidavits, declarations. Fees: standardized fee schedule. International recognition: notarized documents recognized abroad with proper authentication. Professional notary services available.', ARRAY['notarization', 'notary public', 'document certification', 'authentication'], ARRAY['notary', 'certification', 'official documents'], 'Notary Public Law No. 68 of 1947', 'Article 15', 'en'),

('Criminal Law Basics for Foreign Residents', 'Legal Procedures', 'Criminal Law', 'Criminal law basics every foreign resident should know. Legal principles: Egyptian criminal law applies to all residents and visitors. Common violations: traffic offenses, visa violations, business violations, public order offenses. Legal rights: right to lawyer, right to interpreter, right to embassy notification. Arrest procedures: immediate lawyer contact, embassy notification. Penalties: fines, imprisonment, deportation. Legal representation essential for criminal matters.', ARRAY['criminal law', 'legal rights', 'arrest procedures', 'criminal defense'], ARRAY['criminal law', 'legal rights', 'defense'], 'Penal Code No. 58 of 1937', 'Article 5', 'en'),

('Traffic Violations and Penalties', 'Legal Procedures', 'Traffic Law', 'Traffic violations and penalties for foreign drivers in Egypt. Common violations: speeding, parking violations, license violations, vehicle registration issues. Penalty structure: fines, license suspension, vehicle impoundment. International driving license: validity and requirements. Accident procedures: police report, insurance notification, embassy contact if needed. Court proceedings: traffic court procedures for serious violations. Legal representation recommended for major violations.', ARRAY['traffic violations', 'driving penalties', 'international license', 'traffic court'], ARRAY['traffic law', 'driving', 'penalties'], 'Traffic Law No. 66 of 1973', 'Article 25', 'en'),

('Contract Dispute Resolution Procedures', 'Legal Procedures', 'Dispute Resolution', 'Contract dispute resolution options in Egypt. Court litigation: Economic Courts for commercial disputes, Civil Courts for general contracts. Alternative dispute resolution: mediation, arbitration through Cairo Regional Centre. Jurisdiction: Egyptian courts for Egypt-based contracts. Evidence requirements: written contracts, correspondence, witness testimony. Enforcement: judgment enforcement through execution courts. International arbitration: available for qualifying disputes.', ARRAY['contract disputes', 'commercial litigation', 'arbitration', 'dispute resolution'], ARRAY['disputes', 'litigation', 'arbitration'], 'Civil and Commercial Procedures Law No. 13 of 1968', 'Article 85', 'en'),

('Small Claims Court Procedures', 'Legal Procedures', 'Small Claims', 'Small claims court procedures for minor disputes. Jurisdiction limits: claims up to EGP 100,000 in Economic Courts summary procedures. Simplified procedures: reduced documentation, faster processing, limited appeals. Eligible claims: commercial debts, service payments, simple contract disputes. Filing requirements: claim form, supporting documents, court fees. Representation: lawyer representation optional for small claims. Time limits: strict deadlines for filing and response.', ARRAY['small claims', 'summary procedures', 'minor disputes', 'simplified litigation'], ARRAY['small claims', 'summary justice', 'minor disputes'], 'Economic Courts Law No. 120 of 2008', 'Article 45', 'en'),

('Mediation and Arbitration Options', 'Legal Procedures', 'Alternative Dispute Resolution', 'Mediation and arbitration alternatives to court litigation. Mediation services: voluntary, confidential, facilitated negotiation. Arbitration types: institutional arbitration (CRCICA), ad hoc arbitration. Arbitration advantages: faster resolution, expert arbitrators, confidentiality, limited appeals. Enforceability: arbitration awards enforceable like court judgments. International arbitration: available for foreign investment disputes. Professional ADR providers available.', ARRAY['mediation', 'arbitration', 'CRCICA', 'alternative dispute resolution'], ARRAY['ADR', 'arbitration', 'mediation'], 'Arbitration Law No. 27 of 1994', 'Article 15', 'en'),

('Legal Costs and Fee Structures', 'Legal Procedures', 'Legal Costs', 'Legal costs and fee structures in Egyptian legal system. Court fees: filing fees, hearing fees, expert fees based on claim value. Lawyer fees: hourly rates (EGP 500-3000), fixed fees, success fees. Additional costs: translation, notarization, expert witnesses, enforcement. Fee agreements: written fee agreements recommended. Cost allocation: losing party typically pays costs. Legal insurance: available for some types of disputes.', ARRAY['legal costs', 'court fees', 'lawyer fees', 'litigation costs'], ARRAY['legal fees', 'costs', 'expenses'], 'Lawyer Fees Law No. 81 of 1996', 'Article 8', 'en'),

('Evidence Requirements in Egyptian Courts', 'Legal Procedures', 'Evidence Law', 'Evidence requirements in Egyptian court proceedings. Types of evidence: documentary, witness testimony, expert evidence, physical evidence. Documentary evidence: contracts, correspondence, official documents. Witness testimony: rules for witness examination, credibility assessment. Expert evidence: court-appointed experts, party experts. Evidence preservation: procedures for preserving evidence. Foreign evidence: authentication requirements for foreign documents.', ARRAY['evidence law', 'documentary evidence', 'witness testimony', 'expert evidence'], ARRAY['evidence', 'proof', 'litigation'], 'Evidence Law No. 25 of 1968', 'Article 12', 'en'),

('Witness Testimony Procedures', 'Legal Procedures', 'Witness Testimony', 'Witness testimony procedures in Egyptian courts. Witness qualification: competency requirements, disqualification grounds. Oath administration: religious or civil oath options. Examination procedures: direct examination, cross-examination, court questioning. Witness protection: limited protection available. Expert witnesses: qualification requirements, court appointment procedures. International witnesses: procedures for foreign witness testimony. Interpretation services available for non-Arabic speakers.', ARRAY['witness testimony', 'court testimony', 'witness examination', 'expert witnesses'], ARRAY['witnesses', 'testimony', 'court procedures'], 'Evidence Law No. 25 of 1968', 'Article 35', 'en'),

('Appeal Processes and Timelines', 'Legal Procedures', 'Appeals', 'Appeal processes and timelines in Egyptian court system. Appeal levels: Courts of Appeal, Court of Cassation. Time limits: 30 days for most appeals, strict deadlines. Appeal grounds: legal errors, procedural violations, factual disputes (limited). Filing requirements: appeal brief, court fees, service on opposing party. Stay of execution: available in some cases pending appeal. Appeal outcomes: affirmation, reversal, remand. Professional legal representation essential for appeals.', ARRAY['appeals', 'court of appeal', 'cassation', 'appeal procedures'], ARRAY['appeals', 'appellate court', 'legal review'], 'Civil and Commercial Procedures Law No. 13 of 1968', 'Article 125', 'en'),

('Enforcement of Foreign Court Judgments', 'Legal Procedures', 'Judgment Enforcement', 'Enforcement of foreign court judgments in Egypt. Recognition requirements: reciprocity, jurisdiction, due process, public policy compliance. Enforcement procedures: application to competent Egyptian court, notice to judgment debtor. Excluded judgments: criminal judgments, administrative decisions, judgments contrary to Egyptian public policy. Professional legal assistance essential. International agreements: bilateral enforcement treaties with some countries.', ARRAY['foreign judgments', 'judgment enforcement', 'international enforcement', 'recognition'], ARRAY['enforcement', 'foreign judgments', 'international law'], 'Civil and Commercial Procedures Law No. 13 of 1968', 'Article 295', 'en'),

('Bankruptcy Protection for Individuals', 'Legal Procedures', 'Personal Bankruptcy', 'Personal bankruptcy protection available for individuals unable to pay debts. Bankruptcy types: liquidation bankruptcy, reorganization procedures. Filing requirements: financial statements, asset lists, creditor lists. Automatic stay: protection from creditor actions upon filing. Asset protection: limited exemptions for essential assets. Discharge: debt relief upon successful completion of proceedings. Professional bankruptcy attorney recommended for complex cases.', ARRAY['personal bankruptcy', 'debt relief', 'financial distress', 'bankruptcy protection'], ARRAY['bankruptcy', 'debt relief', 'insolvency'], 'Bankruptcy Law No. 11 of 2018', 'Article 25', 'en'),

('Consumer Protection Laws for Foreigners', 'Legal Procedures', 'Consumer Rights', 'Consumer protection laws apply to all residents including foreigners. Protected rights: fair pricing, product quality, accurate advertising, warranty protection. Complaint procedures: Consumer Protection Agency, specialized courts. Dispute resolution: mediation services, small claims procedures. Defective products: liability for defective products, recall procedures. Service disputes: telecommunications, utilities, financial services. Professional consumer advocacy available.', ARRAY['consumer protection', 'consumer rights', 'product liability', 'consumer complaints'], ARRAY['consumer protection', 'consumer rights', 'product safety'], 'Consumer Protection Law No. 181 of 2018', 'Article 15', 'en');