-- Populate legal database with comprehensive articles for foreign nationals in Egypt

-- Immigration & Residence Law Articles (19 new)
INSERT INTO legal_knowledge (title, category, subcategory, content, keywords, tags, law_reference, article_number, language) VALUES
('Tourist Visa Extensions in Egypt', 'Immigration', 'Visas', 'Learn how to extend your tourist visa in Egypt. Tourist visas can typically be extended for up to 6 months total. Visit the Passport and Immigration Department (Mogamma) in Tahrir Square or local immigration offices. Required documents include passport, visa extension form, passport photos, and extension fees. Process takes 1-3 business days. Extensions must be applied for before current visa expires to avoid overstay penalties.', ARRAY['tourist visa', 'visa extension', 'immigration', 'passport', 'mogamma'], ARRAY['visas', 'tourism', 'extensions'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 15', 'en'),

('Work Permit Applications for Foreigners', 'Immigration', 'Work Permits', 'Complete guide to obtaining work permits in Egypt. Foreign nationals must obtain work permits before starting employment. Applications submitted through Ministry of Manpower and Immigration. Required documents: employment contract, educational certificates, medical certificate, passport copies, criminal background check. Processing time: 30-60 days. Annual renewal required. Penalties for working without permits include fines and deportation.', ARRAY['work permit', 'employment', 'ministry of manpower', 'foreign workers'], ARRAY['employment', 'permits', 'legal work'], 'Law No. 12 of 2003 (Labor Law)', 'Article 28', 'en'),

('Investor Visa Requirements ($100K+ Investment)', 'Immigration', 'Investment Visas', 'Investor visas available for foreign nationals investing $100,000+ in Egyptian businesses or real estate. Applications through General Authority for Investment and Free Zones (GAFI). Investment must be maintained for minimum 3 years. Provides pathway to permanent residence. Required documentation: investment proof, business plan, financial statements, due diligence reports. Family members eligible for dependent visas.', ARRAY['investor visa', 'investment', 'GAFI', 'permanent residence', '100000 dollars'], ARRAY['investment', 'business', 'residence'], 'Investment Law No. 72 of 2017', 'Article 61', 'en'),

('Family Reunification Procedures', 'Immigration', 'Family Visas', 'Family reunification allows Egyptian citizens and permanent residents to sponsor family members. Eligible relatives: spouse, children under 21, parents over 60. Sponsor must prove financial capacity and provide accommodation. Required documents: marriage/birth certificates, sponsor financial statements, accommodation proof, medical certificates. Processing time: 60-90 days through Ministry of Interior.', ARRAY['family reunification', 'spouse visa', 'family visa', 'sponsorship'], ARRAY['family', 'reunification', 'immigration'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 25', 'en'),

('Student Visa and Study Permits', 'Immigration', 'Student Visas', 'Student visas required for foreign nationals studying in Egypt. Applications through Egyptian consulates or universities. Required documents: university acceptance letter, financial proof, academic transcripts, medical certificate, passport photos. Valid for duration of studies with annual renewal. Part-time work allowed with university permission. Conversion to work visa possible after graduation.', ARRAY['student visa', 'study permit', 'university', 'education'], ARRAY['education', 'students', 'permits'], 'Higher Education Law No. 49 of 1972', 'Article 76', 'en'),

('Temporary Residence Permits', 'Immigration', 'Residence Permits', 'Temporary residence permits for stays exceeding tourist visa duration. Valid for 1-5 years depending on purpose. Categories: employment, investment, study, family. Applications through Passport and Immigration Department. Required documents: purpose justification, financial proof, accommodation evidence, medical certificate, criminal background check. Renewal possible with continued eligibility.', ARRAY['temporary residence', 'residence permit', 'long term stay'], ARRAY['residence', 'permits', 'temporary'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 18', 'en'),

('Permanent Residence Pathways', 'Immigration', 'Permanent Residence', 'Permanent residence available after 5 years continuous temporary residence or through investment/marriage. Benefits include unrestricted employment, property ownership rights, and social services access. Application requirements: 5-year residence history, clean criminal record, Arabic language proficiency, financial stability proof. Processing through Ministry of Interior takes 6-12 months.', ARRAY['permanent residence', 'citizenship pathway', 'long term residence'], ARRAY['permanent', 'residence', 'immigration'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 20', 'en'),

('Egyptian Citizenship Eligibility and Process', 'Immigration', 'Citizenship', 'Egyptian citizenship through naturalization requires 10 years continuous residence (5 years if married to Egyptian). Applicants must demonstrate Arabic proficiency, financial stability, clean criminal record, and knowledge of Egyptian history. Dual citizenship not recognized - must renounce previous citizenship. Application through Ministry of Interior Nationality Department. Processing time: 12-24 months.', ARRAY['egyptian citizenship', 'naturalization', 'dual citizenship'], ARRAY['citizenship', 'naturalization', 'nationality'], 'Nationality Law No. 26 of 1975', 'Article 7', 'en'),

('Visa Overstay Penalties and Solutions', 'Immigration', 'Violations', 'Visa overstay penalties: EGP 600-3000 depending on duration and visa type. Over 30 days overstay may result in entry ban (6 months to 5 years). Solutions: pay fines at immigration office, obtain legal assistance, apply for visa amnesty programs if available. Voluntary departure may reduce penalties. Seek legal advice before leaving Egypt to avoid future entry problems.', ARRAY['visa overstay', 'immigration penalties', 'fines', 'entry ban'], ARRAY['violations', 'penalties', 'overstay'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 42', 'en'),

('Entry and Exit Requirements by Nationality', 'Immigration', 'Border Control', 'Entry requirements vary by nationality. EU, US, Canadian citizens: visa on arrival available. GCC citizens: visa-free entry. Other nationalities: pre-approved visa required. All visitors need passport valid 6+ months, return ticket, accommodation proof. Exit requirements: departure tax payment, no legal impediments. Check embassy websites for current requirements as policies change frequently.', ARRAY['entry requirements', 'visa on arrival', 'nationality', 'border control'], ARRAY['entry', 'visas', 'travel'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 5', 'en'),

('Transit Visa Requirements', 'Immigration', 'Transit', 'Transit visas required for passengers connecting through Egypt with layovers exceeding 24 hours or leaving airport. Free 48-hour transit visa available at Cairo Airport for eligible nationalities. Required documents: confirmed onward ticket, transit visa application, passport photos. Transit passengers cannot leave designated airport areas without proper visa. Check airline and airport transit policies.', ARRAY['transit visa', 'layover', 'cairo airport', 'connecting flights'], ARRAY['transit', 'airport', 'travel'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 8', 'en'),

('Diplomatic and Official Visa Procedures', 'Immigration', 'Diplomatic Visas', 'Diplomatic and official visas for government officials and diplomats. Applications through Ministry of Foreign Affairs and embassies. Required documents: diplomatic note, official letter, diplomatic passport. Multiple entry visas typically granted. Diplomatic immunity and privileges apply. Family members eligible for dependent diplomatic visas. Reciprocal arrangements apply based on bilateral agreements.', ARRAY['diplomatic visa', 'official visa', 'diplomatic immunity', 'foreign affairs'], ARRAY['diplomatic', 'official', 'government'], 'Vienna Convention on Diplomatic Relations 1961', 'Article 9', 'en'),

('Medical Visa for Treatment', 'Immigration', 'Medical Visas', 'Medical visas for foreign patients seeking treatment in Egypt. Required documents: medical report from home country, Egyptian hospital acceptance letter, financial guarantee, medical insurance, treatment plan. Visa duration based on treatment length. Accompanying family member visas available. Extensions possible with medical justification. Payment guarantees required for treatment costs.', ARRAY['medical visa', 'medical treatment', 'healthcare', 'hospital'], ARRAY['medical', 'healthcare', 'treatment'], 'Health Insurance Law No. 2 of 2018', 'Article 45', 'en'),

('Religious Visa for Pilgrimage', 'Immigration', 'Religious Visas', 'Religious visas for pilgrimage to Islamic sites in Egypt. Applications through Ministry of Endowments and Religious Affairs. Group applications processed through licensed tour operators. Required documents: religious organization letter, pilgrimage itinerary, accommodation bookings, health certificate. Seasonal restrictions may apply during Hajj periods. Special provisions for elderly and disabled pilgrims.', ARRAY['religious visa', 'pilgrimage', 'islamic sites', 'religious tourism'], ARRAY['religious', 'pilgrimage', 'tourism'], 'Religious Endowments Law No. 80 of 1971', 'Article 12', 'en'),

('Deportation Laws and Appeal Processes', 'Immigration', 'Deportation', 'Deportation ordered for serious immigration violations, criminal activity, or national security concerns. Deportation process: detention, administrative hearing, appeal period (30 days), execution. Appeals filed with Administrative Court. Legal representation recommended. Deportees may face entry bans (1-10 years). Voluntary departure may be negotiated to avoid formal deportation record.', ARRAY['deportation', 'immigration violations', 'appeal process', 'legal representation'], ARRAY['deportation', 'violations', 'appeals'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 45', 'en'),

('Border Crossing Procedures', 'Immigration', 'Border Control', 'Border crossing procedures at all entry points. Required documents: valid passport, visa (if required), customs declaration, health certificates (if applicable). Biometric data collection at major airports. Customs inspections for goods exceeding duty-free limits. Currency declaration required for amounts over $10,000. Digital immigration cards replacing paper forms at most locations.', ARRAY['border crossing', 'customs', 'immigration control', 'entry points'], ARRAY['borders', 'customs', 'entry'], 'Customs Law No. 207 of 2020', 'Article 18', 'en'),

('Visa Fee Structures and Payment Methods', 'Immigration', 'Fees', 'Visa fees vary by type and nationality. Tourist visa: $25-60, Business visa: $60-150, Residence permit: $200-500. Payment methods: cash (USD/EUR), bank transfer, online payment (selected embassies). Reciprocity fees apply for some nationalities. Processing fees non-refundable. Additional fees for expedited processing, multiple entries, and extensions. Check current rates at embassies.', ARRAY['visa fees', 'payment methods', 'processing fees', 'reciprocity'], ARRAY['fees', 'payment', 'costs'], 'Consular Fees Decree 2023', 'Schedule A', 'en'),

('Required Health Certificates and Vaccinations', 'Immigration', 'Health Requirements', 'Health certificates required for residence permits and some visa types. Yellow fever vaccination mandatory for travelers from affected countries. COVID-19 requirements vary (check current regulations). Medical examination by approved physicians for work permits and residence applications. Health insurance proof required for some visa categories. Tuberculosis screening for long-term residents.', ARRAY['health certificate', 'vaccinations', 'medical examination', 'health insurance'], ARRAY['health', 'medical', 'vaccinations'], 'Public Health Law No. 137 of 1958', 'Article 28', 'en'),

('Police Clearance Certificate Requirements', 'Immigration', 'Documentation', 'Police clearance certificates required for residence permits, work permits, and citizenship applications. Must be from all countries of residence in past 5 years. Certificates must be apostilled or legalized, translated to Arabic by certified translator. Validity: 6 months from issue date. FBI background checks accepted from US citizens. Interpol clearances required for some applications.', ARRAY['police clearance', 'background check', 'criminal record', 'apostille'], ARRAY['clearance', 'background', 'documentation'], 'Law No. 89 of 1960 (Entry, Exit and Residence of Foreigners)', 'Article 12', 'en');

-- Real Estate for Foreigners Articles (19 new)
INSERT INTO legal_knowledge (title, category, subcategory, content, keywords, tags, law_reference, article_number, language) VALUES
('Property Ownership Restrictions by Nationality', 'Real Estate', 'Ownership Rights', 'Foreign property ownership restrictions vary by nationality and property type. Arabs and foreigners married to Egyptians: unrestricted ownership. Other foreigners: maximum 2 residential units per person, commercial property allowed with restrictions. Agricultural land ownership prohibited for all foreigners. Properties must be registered with Real Estate Publicity Department. Inheritance rights preserved for foreign-owned property.', ARRAY['property ownership', 'foreign ownership', 'ownership restrictions', 'nationality'], ARRAY['ownership', 'restrictions', 'nationality'], 'Real Estate Law No. 230 of 1996', 'Article 6', 'en'),

('Rental Agreement Essentials for Foreigners', 'Real Estate', 'Rental', 'Rental agreements must be in Arabic (English translation acceptable). Essential clauses: rental amount, payment terms, duration, maintenance responsibilities, termination conditions. Contracts registered with Real Estate Tax Authority for legal protection. Deposit typically 1-2 months rent. Utilities arrangement specified. Foreign tenants have same rights as Egyptian tenants under rent control laws.', ARRAY['rental agreement', 'lease contract', 'tenant rights', 'rent control'], ARRAY['rental', 'lease', 'contracts'], 'Rent Law No. 4 of 1996', 'Article 15', 'en'),

('Property Inheritance Laws for Foreigners', 'Real Estate', 'Inheritance', 'Foreign-owned property subject to Egyptian inheritance laws unless bilateral treaty exists. Islamic inheritance law may apply regardless of owner religion. Non-Muslim foreigners can specify inheritance distribution through registered will. Property can be inherited by foreign heirs with proper documentation. Inheritance tax applies: 5-10% depending on relationship. Probate process through Family Court.', ARRAY['property inheritance', 'inheritance law', 'foreign heirs', 'probate'], ARRAY['inheritance', 'wills', 'probate'], 'Inheritance Law No. 77 of 1943', 'Article 12', 'en'),

('Real Estate Tax Obligations for Foreign Owners', 'Real Estate', 'Taxation', 'Foreign property owners subject to same tax obligations as Egyptians. Property tax: 10% of annual rental value (actual or estimated). Tax assessed by Real Estate Tax Authority. Payment due annually by June 30. Late payment penalties: 2% monthly. Foreign owners must file tax returns. Properties used for personal residence eligible for exemptions. Professional tax advice recommended.', ARRAY['property tax', 'real estate tax', 'tax obligations', 'foreign owners'], ARRAY['taxation', 'property tax', 'compliance'], 'Real Estate Tax Law No. 196 of 2008', 'Article 3', 'en'),

('Property Registration and Title Deed Process', 'Real Estate', 'Registration', 'Property registration mandatory for legal ownership. Process: preliminary contract, due diligence, final contract, registration with Real Estate Publicity Department. Required documents: seller title deed, tax clearances, survey report, buyer identification. Registration fees: 3% of property value plus administrative costs. Foreign buyers need legal representation. Process takes 30-60 days.', ARRAY['property registration', 'title deed', 'real estate publicity', 'legal ownership'], ARRAY['registration', 'title deed', 'ownership'], 'Real Estate Law No. 230 of 1996', 'Article 18', 'en'),

('Mortgages and Financing for Foreign Buyers', 'Real Estate', 'Financing', 'Limited mortgage options for foreign buyers. Egyptian banks offer mortgages to residents with local income. Loan-to-value ratios: 70-80% for residents, lower for non-residents. Interest rates: 12-18% annually. Required documents: income proof, bank statements, property valuation, residence permit. Alternative financing through developer payment plans or international lenders.', ARRAY['mortgage', 'property financing', 'foreign buyers', 'bank loans'], ARRAY['mortgages', 'financing', 'loans'], 'Banking Law No. 194 of 2020', 'Article 65', 'en'),

('Property Management for Non-Resident Owners', 'Real Estate', 'Management', 'Property management services essential for non-resident owners. Services include: rent collection, maintenance, tenant relations, tax compliance, legal representation. Management fees: 5-15% of rental income. Power of attorney required for manager authority. Regular reporting and financial statements provided. Professional property management companies licensed by Ministry of Housing.', ARRAY['property management', 'non-resident owners', 'rental management', 'power of attorney'], ARRAY['management', 'rental', 'non-resident'], 'Real Estate Law No. 230 of 1996', 'Article 25', 'en'),

('Commercial Real Estate Investment Rules', 'Real Estate', 'Commercial Property', 'Commercial property investment by foreigners subject to specific regulations. Industrial zones and free zones offer special incentives. Required approvals from General Authority for Investment (GAFI) for large investments. Foreign ownership percentage restrictions in some sectors. Due diligence on zoning compliance essential. Commercial property registration process similar to residential but additional permits required.', ARRAY['commercial real estate', 'commercial property', 'GAFI', 'investment rules'], ARRAY['commercial', 'investment', 'business'], 'Investment Law No. 72 of 2017', 'Article 25', 'en'),

('Land Ownership vs Usufruct Rights', 'Real Estate', 'Land Rights', 'Foreign land ownership restricted - usufruct rights alternative. Usufruct grants use and profit rights without ownership. Maximum term: 50 years (renewable). Usufruct can be sold, mortgaged, inherited. Registration required with Real Estate Publicity Department. Conversion to ownership possible for eligible foreigners. Agricultural land strictly prohibited for foreign ownership under any arrangement.', ARRAY['land ownership', 'usufruct rights', 'land rights', 'agricultural land'], ARRAY['land', 'usufruct', 'rights'], 'Civil Code No. 131 of 1948', 'Article 990', 'en'),

('Property Dispute Resolution Procedures', 'Real Estate', 'Disputes', 'Property disputes resolved through Egyptian court system or arbitration. Common disputes: ownership claims, construction defects, rent disputes, boundary issues. Court process: filing complaint, preliminary hearings, evidence presentation, judgment. Alternative dispute resolution: mediation, arbitration through Cairo Regional Centre for International Commercial Arbitration. Legal representation mandatory for foreigners.', ARRAY['property disputes', 'real estate litigation', 'arbitration', 'legal disputes'], ARRAY['disputes', 'litigation', 'courts'], 'Civil and Commercial Procedures Law No. 13 of 1968', 'Article 180', 'en'),

('Real Estate Agent Regulations and Licensing', 'Real Estate', 'Professional Services', 'Real estate agents must be licensed by Real Estate Development Fund. Agent responsibilities: property verification, legal compliance, contract preparation, registration assistance. Commission rates: 2-5% of property value (negotiable). Foreign buyers advised to use licensed agents with foreign client experience. Agent liability for misrepresentation or fraud. Professional indemnity insurance recommended.', ARRAY['real estate agent', 'agent licensing', 'property agent', 'commission'], ARRAY['agents', 'licensing', 'professional'], 'Real Estate Development Law No. 15 of 2017', 'Article 48', 'en'),

('Property Valuation and Appraisal Requirements', 'Real Estate', 'Valuation', 'Professional property valuation required for: mortgages, taxation, insurance, legal disputes. Licensed appraisers certified by Ministry of Justice. Valuation methods: market comparison, income approach, cost approach. Valuation reports valid for 6 months. Foreign owners should use certified appraisers familiar with foreign ownership regulations. Valuation disputes resolved through expert committee system.', ARRAY['property valuation', 'property appraisal', 'licensed appraiser', 'valuation report'], ARRAY['valuation', 'appraisal', 'assessment'], 'Real Estate Appraisal Law No. 56 of 2014', 'Article 8', 'en'),

('Construction Permits for Foreign Property Owners', 'Real Estate', 'Construction', 'Construction permits required for any building modifications or new construction. Applications through local building authority (hay). Required documents: architectural plans, structural drawings, utility connections, environmental clearances. Foreign owners need Egyptian architect/engineer stamps. Construction supervision mandatory. Completion certificates required before occupancy. Violations subject to demolition orders.', ARRAY['construction permit', 'building permit', 'architectural plans', 'construction supervision'], ARRAY['construction', 'permits', 'building'], 'Unified Building Law No. 119 of 2008', 'Article 15', 'en'),

('Selling Property as a Foreigner', 'Real Estate', 'Property Sales', 'Foreign property owners can freely sell their property. Capital gains tax: 10% if sold within 5 years, exempt after 5 years. Required documents: title deed, tax clearances, property survey, identification documents. Buyer due diligence recommended. Sale proceeds can be transferred abroad with proper documentation. Professional legal assistance advisable for complex transactions.', ARRAY['property sale', 'selling property', 'capital gains tax', 'foreign sellers'], ARRAY['sales', 'selling', 'capital gains'], 'Income Tax Law No. 91 of 2005', 'Article 25', 'en'),

('Property Insurance Requirements', 'Real Estate', 'Insurance', 'Property insurance not mandatory but highly recommended. Coverage types: fire, theft, natural disasters, third-party liability. Insurance companies licensed by Financial Regulatory Authority. Foreign owners should ensure policies cover international claims. Mortgage lenders typically require comprehensive insurance. Claims process requires police reports for theft/damage. Professional advice on coverage limits recommended.', ARRAY['property insurance', 'home insurance', 'insurance coverage', 'insurance claims'], ARRAY['insurance', 'coverage', 'protection'], 'Insurance Law No. 10 of 1981', 'Article 45', 'en'),

('Utilities Setup and Transfer Procedures', 'Real Estate', 'Utilities', 'Utility connections required for electricity, water, gas, telephone/internet. Applications through respective utility companies. Required documents: property ownership proof, identification, previous bills clearance. Deposits required for new connections. Foreign owners can have utilities in their name with residence permit. Automatic payment systems available. Disconnection procedures for non-payment clearly defined.', ARRAY['utilities', 'electricity', 'water', 'gas', 'utility connection'], ARRAY['utilities', 'connections', 'services'], 'Electricity Law No. 87 of 2015', 'Article 28', 'en'),

('Community Fees and Maintenance Obligations', 'Real Estate', 'Community Living', 'Community fees (maintenance fees) common in gated communities and apartment buildings. Fees cover: security, maintenance, utilities, amenities. Payment typically monthly or quarterly. Property owners responsible for fees regardless of occupancy. Unpaid fees can result in service suspension or legal action. Foreign owners should understand fee structures before purchase. Community bylaws legally binding.', ARRAY['community fees', 'maintenance fees', 'gated community', 'apartment building'], ARRAY['community', 'maintenance', 'fees'], 'Real Estate Law No. 230 of 1996', 'Article 32', 'en'),

('Property Development Joint Ventures', 'Real Estate', 'Development', 'Foreign participation in property development through joint ventures with Egyptian companies. Foreign ownership typically limited to 49% unless special approvals obtained. Joint venture agreements must specify profit sharing, management responsibilities, exit strategies. GAFI approval required for large developments. Due diligence on Egyptian partners essential. Professional legal and financial advice mandatory.', ARRAY['joint venture', 'property development', 'foreign investment', 'development projects'], ARRAY['development', 'joint venture', 'investment'], 'Investment Law No. 72 of 2017', 'Article 35', 'en'),

('Real Estate Investment Fund Participation', 'Real Estate', 'Investment Funds', 'Real estate investment funds (REIFs) allow foreign participation in Egyptian property markets. Funds trade on Egyptian Exchange. Minimum investment amounts vary by fund. Professional fund management reduces individual property management burden. Dividend distributions from rental income and capital appreciation. Foreign investors subject to capital gains tax on fund distributions. Financial advisor consultation recommended.', ARRAY['real estate investment fund', 'REIF', 'Egyptian Exchange', 'property investment'], ARRAY['investment funds', 'REIF', 'portfolio'], 'Capital Market Law No. 95 of 1992', 'Article 82', 'en');

-- Employment Law for Foreigners Articles (19 new)
INSERT INTO legal_knowledge (title, category, subcategory, content, keywords, tags, law_reference, article_number, language) VALUES
('Work Permit Categories and Requirements', 'Employment', 'Work Permits', 'Egypt offers multiple work permit categories: temporary (1 year), renewable (up to 5 years), and permanent. Requirements vary by category: employment contract, educational certificates, medical fitness, criminal background check. Applications through Ministry of Manpower and Immigration. Processing time: 30-60 days. Employer must justify hiring foreign worker over Egyptian. Work permit tied to specific employer and job position.', ARRAY['work permit', 'employment permit', 'foreign workers', 'ministry of manpower'], ARRAY['permits', 'employment', 'foreign workers'], 'Labor Law No. 12 of 2003', 'Article 28', 'en'),

('Employment Contract Mandatory Clauses', 'Employment', 'Contracts', 'Employment contracts must include: job description, salary details, working hours, probation period, termination conditions, benefits package. Contracts in Arabic required (English translation acceptable). Maximum probation period: 3 months for most positions. Notice periods: 2 months for indefinite contracts. Contracts must comply with Egyptian Labor Law minimum standards. Professional contract review recommended.', ARRAY['employment contract', 'job contract', 'contract clauses', 'probation period'], ARRAY['contracts', 'employment terms', 'legal requirements'], 'Labor Law No. 12 of 2003', 'Article 75', 'en'),

('Social Insurance Enrollment for Foreigners', 'Employment', 'Social Insurance', 'Foreign workers must enroll in Egyptian social insurance system. Coverage includes: medical insurance, work injury insurance, pension contributions. Employee contribution: 14% of salary, employer: 26%. Benefits: medical care, disability benefits, pension after 15 years contribution. Foreign workers can claim refund of contributions if leaving Egypt permanently. Registration required within 30 days of employment start.', ARRAY['social insurance', 'medical insurance', 'pension', 'insurance enrollment'], ARRAY['insurance', 'social security', 'benefits'], 'Social Insurance Law No. 79 of 1975', 'Article 15', 'en'),

('Annual Leave and Holiday Entitlements', 'Employment', 'Leave Benefits', 'Foreign employees entitled to same leave benefits as Egyptians. Annual leave: minimum 21 days per year (increases with tenure). Public holidays: approximately 15 days annually including religious holidays. Sick leave: up to 180 days per year (first 90 days paid). Maternity leave: 90 days for female employees. Leave accumulation and cash-out rules apply. Employer cannot deny leave without legal justification.', ARRAY['annual leave', 'holiday entitlement', 'sick leave', 'maternity leave'], ARRAY['leave', 'holidays', 'benefits'], 'Labor Law No. 12 of 2003', 'Article 85', 'en'),

('Overtime Regulations and Compensation', 'Employment', 'Working Hours', 'Standard working hours: 8 hours/day, 48 hours/week. Overtime payment: 135% of hourly rate for first 2 hours, 170% thereafter. Ramadan hours: 6 hours/day for Muslim workers. Night shift premium: 25% additional. Maximum overtime: 2 hours/day except emergencies. Weekly rest day mandatory (typically Friday). Overtime records must be maintained by employers.', ARRAY['overtime', 'working hours', 'overtime pay', 'night shift'], ARRAY['overtime', 'compensation', 'working time'], 'Labor Law No. 12 of 2003', 'Article 95', 'en'),

('Termination Procedures and Severance Pay', 'Employment', 'Termination', 'Employment termination procedures: notice period (2 months for indefinite contracts), severance pay calculation, final settlement. Severance pay: 1 month salary for each year of service. Termination for cause requires documented justification. Wrongful termination claims through labor courts. End-of-service benefits include: unused leave payment, gratuity, social insurance refunds. Professional legal advice recommended for complex cases.', ARRAY['termination', 'severance pay', 'end of service', 'wrongful termination'], ARRAY['termination', 'severance', 'employment end'], 'Labor Law No. 12 of 2003', 'Article 125', 'en'),

('Workplace Safety Regulations', 'Employment', 'Safety', 'Employers must provide safe working environment complying with Egyptian safety standards. Required safety measures: protective equipment, safety training, hazard identification, emergency procedures. Employee rights: refuse unsafe work, report hazards, safety training. Work injury compensation through social insurance. Safety inspections by Ministry of Manpower. Violations result in fines and work suspension orders.', ARRAY['workplace safety', 'safety regulations', 'work injury', 'safety training'], ARRAY['safety', 'workplace protection', 'occupational health'], 'Labor Law No. 12 of 2003', 'Article 135', 'en'),

('Discrimination and Harassment Protections', 'Employment', 'Rights Protection', 'Egyptian labor law prohibits discrimination based on religion, gender, nationality, political opinion. Sexual harassment specifically criminalized with penalties up to 5 years imprisonment. Foreign workers have same protection rights. Complaint procedures: internal grievance, labor office complaints, court proceedings. Employers must establish anti-harassment policies. Whistleblower protections available for good faith reports.', ARRAY['discrimination', 'harassment', 'sexual harassment', 'employee rights'], ARRAY['discrimination', 'harassment', 'employee protection'], 'Labor Law No. 12 of 2003', 'Article 145', 'en'),

('Professional Licensing for Foreign Workers', 'Employment', 'Professional Licenses', 'Certain professions require licensing: doctors, engineers, lawyers, pharmacists, accountants. Foreign professionals must obtain Egyptian practice licenses through relevant professional syndicates. Requirements: qualification recognition, examination (sometimes), local sponsor, licensing fees. Temporary practice permits available for short-term assignments. Professional license renewal required annually or biannually depending on profession.', ARRAY['professional license', 'practice license', 'professional syndicates', 'qualification recognition'], ARRAY['licensing', 'professional practice', 'qualifications'], 'Professional Practice Laws (Various)', 'Article 5', 'en'),

('Tax Obligations for Foreign Employees', 'Employment', 'Taxation', 'Foreign employees subject to Egyptian income tax on Egyptian-sourced income. Tax rates: progressive scale 10-25%. Tax year: July 1 - June 30. Employer withholding required. Annual tax return filing mandatory. Double taxation treaties may provide relief. Exemptions available for certain allowances. Tax residency determined by presence exceeding 183 days annually. Professional tax advice recommended.', ARRAY['income tax', 'tax obligations', 'tax return', 'double taxation'], ARRAY['taxation', 'income tax', 'tax compliance'], 'Income Tax Law No. 91 of 2005', 'Article 15', 'en'),

('Health Insurance Requirements', 'Employment', 'Health Benefits', 'Employers must provide health insurance coverage for foreign employees. Coverage through social insurance system or private insurance. Minimum coverage: basic medical care, hospitalization, emergency treatment. Family coverage typically additional cost. Pre-existing conditions may have waiting periods. International health insurance acceptable if meeting minimum standards. Claims procedures and network providers specified in policy.', ARRAY['health insurance', 'medical coverage', 'employee benefits', 'medical care'], ARRAY['health insurance', 'medical benefits', 'healthcare'], 'Social Insurance Law No. 79 of 1975', 'Article 35', 'en'),

('Maternity and Paternity Leave Rights', 'Employment', 'Family Leave', 'Maternity leave: 90 days full pay (can be extended unpaid). Paternity leave: 3 days paid leave. Nursing mothers: 2 hours daily nursing time for 18 months. Pregnancy discrimination prohibited. Job protection during maternity leave guaranteed. Childcare leave: unpaid leave up to 2 years (job not guaranteed). Adoption leave: same as maternity leave for adoptive mothers.', ARRAY['maternity leave', 'paternity leave', 'pregnancy rights', 'childcare leave'], ARRAY['maternity', 'family leave', 'parental rights'], 'Labor Law No. 12 of 2003', 'Article 155', 'en'),

('Trade Union Membership Rights', 'Employment', 'Union Rights', 'Foreign workers have right to join Egyptian trade unions. Union membership voluntary but provides collective bargaining representation. Union benefits: wage negotiation, grievance representation, legal assistance. Union dues typically 1% of salary. Strikes legal with proper procedures. Union discrimination prohibited. International labor standards recognized. Professional associations separate from trade unions.', ARRAY['trade union', 'union membership', 'collective bargaining', 'worker rights'], ARRAY['unions', 'collective bargaining', 'worker representation'], 'Trade Union Law No. 35 of 1976', 'Article 8', 'en'),

('Workplace Injury Compensation', 'Employment', 'Injury Claims', 'Workplace injuries covered by social insurance system. Compensation includes: medical treatment, disability benefits, death benefits. Reporting requirements: immediate notification to employer and social insurance. Medical treatment at approved facilities. Permanent disability assessment by medical committee. Death benefits for family members. Employer liability for unsafe conditions. Claims process through social insurance administration.', ARRAY['workplace injury', 'injury compensation', 'disability benefits', 'work accident'], ARRAY['injury compensation', 'workplace accidents', 'disability'], 'Social Insurance Law No. 79 of 1975', 'Article 65', 'en'),

('Employment Dispute Resolution', 'Employment', 'Dispute Resolution', 'Employment disputes resolved through: internal grievance procedures, labor office mediation, labor courts. Mediation services free through Ministry of Manpower. Labor court jurisdiction over: wage disputes, termination claims, discrimination cases. Appeal process available. Legal representation recommended for complex cases. Time limits apply for filing complaints. Enforcement of judgments through execution courts.', ARRAY['employment disputes', 'labor court', 'grievance procedure', 'mediation'], ARRAY['disputes', 'labor court', 'conflict resolution'], 'Labor Law No. 12 of 2003', 'Article 185', 'en'),

('Non-Compete Clauses and Restrictions', 'Employment', 'Employment Restrictions', 'Non-compete clauses valid if reasonable in scope, duration, and geography. Maximum enforceability: 2 years post-employment. Employer must prove legitimate business interests. Compensation required during non-compete period. Trade secret protection enforceable. Non-solicitation of clients/employees permitted with restrictions. Court review of unreasonable restrictions. International enforceability limited to Egyptian territory.', ARRAY['non-compete', 'employment restrictions', 'trade secrets', 'non-solicitation'], ARRAY['non-compete', 'employment restrictions', 'confidentiality'], 'Civil Code No. 131 of 1948', 'Article 165', 'en'),

('Freelancing and Self-Employment Rules', 'Employment', 'Self-Employment', 'Foreign nationals can engage in freelancing with proper permits. Commercial registration required for business activities. Tax registration mandatory. Professional services may require syndicate membership. Freelance income subject to Egyptian taxation. Social insurance enrollment optional but recommended. Business bank account required. Contract terms with clients should specify tax responsibilities. Regular reporting to tax authorities required.', ARRAY['freelancing', 'self-employment', 'commercial registration', 'independent contractor'], ARRAY['freelancing', 'self-employment', 'independent work'], 'Commercial Law No. 17 of 1999', 'Article 25', 'en'),

('Domestic Worker Employment Laws', 'Employment', 'Domestic Workers', 'Domestic worker employment regulated by special provisions. Written contracts required specifying: duties, working hours, accommodation, wages, leave entitlements. Maximum working hours: 10 hours/day with breaks. Weekly rest day mandatory. Wage protection through labor office registration. Termination notice: 1 month. Dispute resolution through specialized labor offices. Worker rights protected under criminal law for abuse cases.', ARRAY['domestic worker', 'domestic employment', 'housemaid', 'domestic help'], ARRAY['domestic workers', 'household employment', 'worker protection'], 'Domestic Workers Law No. 11 of 2017', 'Article 8', 'en'),

('Executive and Managerial Employment Terms', 'Employment', 'Executive Employment', 'Executive positions may have enhanced contract terms: longer notice periods, severance packages, benefit enhancements. Stock options and equity participation permitted. Confidentiality and non-disclosure agreements common. Performance-based compensation structures allowed. International assignment terms negotiable. Executive search firms must be licensed. Director and officer insurance recommended. Professional indemnity considerations for certain positions.', ARRAY['executive employment', 'management contracts', 'executive compensation', 'stock options'], ARRAY['executive', 'management', 'senior positions'], 'Companies Law No. 159 of 1981', 'Article 85', 'en');

-- Continue with remaining categories (Business, Family Law, Legal Procedures) in next batch due to length limits...